"""`python -m comparison` (via `just compare`) — run the agreement gate and
benchmarks against the live stack, then regenerate docs/COMPARISON.md.

The matrix is never edited by hand: numbers exist only with provenance.
"""

from __future__ import annotations

import argparse
import asyncio
import datetime
import logging
from pathlib import Path

from comparison.bench import AGREEMENT_TOLERANCE_M, check_agreement, run_benchmarks

_TEMPLATE = """\
# The same question, three information models

*Generated by `just compare` on {date} — do not edit by hand; numbers
without provenance are adjectives.*

Question asked through every adapter: **what is the current end-effector
pose?** One UR5 twin, one telemetry stream, one feeder computing FK once
(fairness rules in AGENTS.md); both structured models update at the same
configured rate (10 Hz).

## Agreement gate

All three adapters answered within {tolerance} m on every axis before any
benchmark ran (x values at gate time: {agreement}). A matrix over
disagreeing adapters is invalid by construction.

## The matrix

| Adapter | Query latency p50 | p95 | Payload bytes/query | Client LOC |
|---------|------------------:|----:|--------------------:|-----------:|
{rows}

## Methodology

- **Latency**: wall clock around each frozen client's `read_pose()`,
  {runs} runs after {warmup} warmup, *connection setup included* — the
  honest unit for a one-shot "what is the pose right now?" query.
- **Payload bytes**: application-payload bytes for one answered query
  (retained MQTT message; HTTP response body; binary-encoded OPC-UA
  DataValues). Protocol framing excluded — comparable orders of magnitude,
  not a packet capture.
- **Client LOC**: non-blank, non-comment, non-docstring lines of the frozen
  clients in `comparison/src/comparison/clients/` — frozen precisely so
  this number is a measurement, not a style contest.
- BaSyx: `eclipsebasyx/aas-environment:2.0.0-milestone-13`, unmodified.
  Empirical API notes (submodel-level ValueOnly PATCH unsupported; values
  must be JSON strings) in `adapters/aas-populator/src/aas_populator/basyx.py`.
- AAS units ride as lightweight Qualifiers and OPC-UA units as a `Unit`
  string property — symmetric ceremony by design (ADR-0004); neither model
  pays for the other's formality.

## What would not generalise

- One asset, one query, localhost transport: relative gaps are meaningful,
  absolute numbers are not.
- The AAS numbers measure BaSyx-the-implementation as much as
  AAS-the-standard; the same caveat applies to asyncua.
- Write paths, discovery, and history — where the standards differ most —
  are out of scope here (see VISION.md).
"""


def render(rows: str, agreement: str, runs: int, warmup: int) -> str:
    return _TEMPLATE.format(
        date=datetime.date.today().isoformat(),
        tolerance=AGREEMENT_TOLERANCE_M,
        agreement=agreement,
        rows=rows,
        runs=runs,
        warmup=warmup,
    )


async def main() -> None:
    logging.getLogger("asyncua").setLevel(logging.ERROR)
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("docs/COMPARISON.md"))
    parser.add_argument("--runs", type=int, default=100)
    parser.add_argument("--warmup", type=int, default=5)
    args = parser.parse_args()

    answers = await check_agreement()
    print("agreement gate ✓")
    results = await run_benchmarks(runs=args.runs, warmup=args.warmup)

    rows = "\n".join(
        f"| {r.name} | {r.p50_ms} ms | {r.p95_ms} ms | {r.payload_bytes} | {r.client_loc} |"
        for r in results
    )
    agreement = ", ".join(f"{name} {pose['x']:+.3f}" for name, pose in answers.items())
    args.output.write_text(render(rows, agreement, args.runs, args.warmup))
    print(f"wrote {args.output}")
    for r in results:
        print(
            f"  {r.name:9s} p50={r.p50_ms}ms p95={r.p95_ms}ms "
            f"bytes={r.payload_bytes} loc={r.client_loc}"
        )


if __name__ == "__main__":
    asyncio.run(main())
